package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_APPLICATION"
   ruleflow-group 'GenerateSearches'
   no-loop true
   when
      not  SearchEntity (code == "SBE_APPLICATION")
      serviceToken : GennyToken( code == "PER_SERVICE")
   then
     	System.out.println("Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

    	SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Application")
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              
                              /* Table Columns */
								.addColumn("PRI_MENTOR_CODE", "Mentor")
								.addColumn("PRI_MENTORING_MEETING_1", "Meeting1")
								.addColumn("PRI_MENTORING_MEETING_2", "Meeting2")
								.addColumn("PRI_MENTORING_MEETING_3", "Meeting3")
								.addColumn("PRI_MENTORING_MEETING_4", "Meeting4")
								.addColumn("PRI_MENTORING_MEETING_5", "Meeting5")
								.addColumn("PRI_MENTORING_MEETING_6", "Meeting6")
								.addColumn("PRI_MENTORING_MEETING_7", "Meeting7")
								.addColumn("PRI_MENTORING_MEETING_8", "Meeting8")
								.addColumn("PRI_MENTORING_MEETING_9", "Meeting9")
								.addColumn("PRI_MENTORING_MEETING_10", "Meeting10")
								.addColumn("PRI_MENTORING_MEETING_11", "Meeting11")
								.addColumn("PRI_MENTORING_MEETING_12", "Meeting12")
								.addColumn("PRI_NEXT_MEETING", "NextMeeting")
                              
                              .setPageStart(0).setPageSize(1);

      searchBE.setRealm(serviceToken.getRealm());

	 insert(searchBE);
     VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());
  	
end
