package life.genny.rules;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.utils.TaskUtils;
import java.util.List;
import java.util.ArrayList;
import life.genny.utils.QuestionUtils;

rule "LNK_AGREE_TO_MENTOR"
	ruleflow-group 'DataProcessing'
	salience 500
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		answer : Answer( attributeCode == "LNK_AGREE_TO_MENTOR" )
		output : OutputParam()
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName()+": Rule fired");

		/* Get Target User BE */
 		String targetCode = answer.getTargetCode();
 		System.out.println("LNK_AGREE_TO_MENTOR:: targetCode = " + targetCode);
 		String value = answer.getValue();
 		System.out.println("LNK_AGREE_TO_MENTOR:: value = " + value);

		if (value.equals("SEL_YES")) {
			QDataAskMessage askMsg = QuestionUtils.getAsks(userToken.getUserCode(), targetCode, "QUE_MENTOR_AGREE_TO_MENTOR_GRP", userToken.getToken());

			if (askMsg != null) {
				askMsg.setToken(userToken.getToken());
				askMsg.setReplace(true);
				VertxUtils.writeMsg("webcmds", askMsg);
			} else {
				System.out.println("Could not fetch ask from cache: QUE_QA_HOST_CPY_REP_GRP");
			}
		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");
end
